import {
  Banknote,
  BarChart3,
  Briefcase,
  CandlestickChart,
  Car,
  CircleDollarSign,
  Coffee,
  Coins,
  CreditCard,
  DollarSign,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Landmark,
  LineChart,
  PiggyBank,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Star,
  Store,
  TrendingUp,
  Wallet,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { IconName } from './types'

const ACCOUNT_ICONS: Record<IconName, LucideIcon> = {
  Wallet,
  CreditCard,
  Landmark,
  PiggyBank,
  Coins,
  TrendingUp,
  DollarSign,
  Banknote,
  CircleDollarSign,
  ShoppingBag,
  ShoppingCart,
  Store,
  Briefcase,
  Home,
  Car,
  GraduationCap,
  Heart,
  Star,
  Smartphone,
  Globe,
  Zap,
  Gift,
  Coffee,
  BarChart3,
  LineChart,
  CandlestickChart,
}

export function AccountIcon({ name, className = 'w-5 h-5' }: { name: string; className?: string }) {
  const Icon = ACCOUNT_ICONS[name as IconName] ?? Wallet
  return <Icon className={className} />
}
